# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: main

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - run: ls -la

    - name: Create Artifact
      run: go build -o palworld-manager main.go

    # todo: how to verify the artifact?
    - name: Check Artifact
      run: ./palworld-manager help

    # todo: convert to oidc
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Upload Versioned Artifact
      run: aws s3 cp ./palworld-manager s3://${{ secretes.AWS_BUCKET }}/build/palworld-manager-${{ github.run_id }}

    - name: Upload Release Artifact
      run: aws s3 cp ./palworld-manager s3://${{ secretes.AWS_BUCKET }}/release/palworld-manager

