# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: main

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Create Artifact
      run: go build -o palworld-manager .

    # todo: how to verify the artifact?
    - name: Check Artifact
      run: palworld-manager help

    - name: Upload Versioned Artifact
      uses: shallwefootball/s3-upload-action@v1.3.3
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: 'palworld-manager'
        destination_dir: build/palworld-manager-${{ github.run_id }}

    - name: Upload Release Artifact
      uses: shallwefootball/s3-upload-action@v1.3.3
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: 'palworld-manager'
        destination_dir: release/palworld-manager
